//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMM2.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSMM2.Resource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonNextRound {
            get {
                return ResourceManager.GetString("ButtonNextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonShuffle {
            get {
                return ResourceManager.GetString("ButtonShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List up player names. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionEntrySheet {
            get {
                return ResourceManager.GetString("DescriptionEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Five Game Match Rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionFiveGameMatch {
            get {
                return ResourceManager.GetString("DescriptionFiveGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionSingleMatch {
            get {
                return ResourceManager.GetString("DescriptionSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 on 3 match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionThreeOnThreeMatch {
            get {
                return ResourceManager.GetString("DescriptionThreeOnThreeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Three Game match rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionTreeGameMatch {
            get {
                return ResourceManager.GetString("DescriptionTreeGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} wins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatSingleMatchLabel {
            get {
                return ResourceManager.GetString("FormatSingleMatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemPlayerModeEntrySheet {
            get {
                return ResourceManager.GetString("ItemPlayerModeEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemPlayerModeNumber {
            get {
                return ResourceManager.GetString("ItemPlayerModeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemPlayerModeRestart {
            get {
                return ResourceManager.GetString("ItemPlayerModeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemResultDraw {
            get {
                return ResourceManager.GetString("ItemResultDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemResultLose {
            get {
                return ResourceManager.GetString("ItemResultLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemResultProgress {
            get {
                return ResourceManager.GetString("ItemResultProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemResultWin {
            get {
                return ResourceManager.GetString("ItemResultWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Five Game Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemRuleFiveGameMatch {
            get {
                return ResourceManager.GetString("ItemRuleFiveGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemRuleSingleMatch {
            get {
                return ResourceManager.GetString("ItemRuleSingleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Three Game Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemRuleThreeGameMatch {
            get {
                return ResourceManager.GetString("ItemRuleThreeGameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 on 3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemRuleThreeOnThreeMatch {
            get {
                return ResourceManager.GetString("ItemRuleThreeOnThreeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label1stMatch {
            get {
                return ResourceManager.GetString("Label1stMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2nd Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label2ndMatch {
            get {
                return ResourceManager.GetString("Label2ndMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3rd Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label3rdMatch {
            get {
                return ResourceManager.GetString("Label3rdMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4th Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label4thMatch {
            get {
                return ResourceManager.GetString("Label4thMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5th Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label5thMatch {
            get {
                return ResourceManager.GetString("Label5thMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BS Match Maker 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelAppTitle {
            get {
                return ResourceManager.GetString("LabelAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelAutoSave {
            get {
                return ResourceManager.GetString("LabelAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCulture {
            get {
                return ResourceManager.GetString("LabelCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDrop {
            get {
                return ResourceManager.GetString("LabelDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelMailAddress {
            get {
                return ResourceManager.GetString("LabelMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelMatchLog {
            get {
                return ResourceManager.GetString("LabelMatchLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelMinimumCondition {
            get {
                return ResourceManager.GetString("LabelMinimumCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As Current Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameAsCurrentGame {
            get {
                return ResourceManager.GetString("LabelNewGameAsCurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Life Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameEnableLifePoint {
            get {
                return ResourceManager.GetString("LabelNewGameEnableLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Sheet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameEntrySheet {
            get {
                return ResourceManager.GetString("LabelNewGameEntrySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameNumberOfPlayer {
            get {
                return ResourceManager.GetString("LabelNewGameNumberOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entry Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGamePlayerEntryMode {
            get {
                return ResourceManager.GetString("LabelNewGamePlayerEntryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGamePlayerPrefix {
            get {
                return ResourceManager.GetString("LabelNewGamePlayerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameRule {
            get {
                return ResourceManager.GetString("LabelNewGameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelNewGameTitle {
            get {
                return ResourceManager.GetString("LabelNewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point Compare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelPointCompare {
            get {
                return ResourceManager.GetString("LabelPointCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept bye match duplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRuleAcceptByeMatchDuplication {
            get {
                return ResourceManager.GetString("LabelRuleAcceptByeMatchDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept gap match duplication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRuleAcceptGapMatchDuplication {
            get {
                return ResourceManager.GetString("LabelRuleAcceptGapMatchDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept gap match duplication except all winners に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRuleAcceptLoserGapMatchDuplication {
            get {
                return ResourceManager.GetString("LabelRuleAcceptLoserGapMatchDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRuleSetting {
            get {
                return ResourceManager.GetString("LabelRuleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Bye Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseByePoint {
            get {
                return ResourceManager.GetString("LabelUseByePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Life point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseLifePoint {
            get {
                return ResourceManager.GetString("LabelUseLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent life pont に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseOpponentLifePoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent match point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseOpponentMatchPoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentMatchPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Opponent win point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseOpponentWinPoint {
            get {
                return ResourceManager.GetString("LabelUseOpponentWinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Win point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelUseWinPoint {
            get {
                return ResourceManager.GetString("LabelUseWinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle except all winners に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWinnerCompare {
            get {
                return ResourceManager.GetString("LabelWinnerCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuAddPlayer {
            get {
                return ResourceManager.GetString("MenuAddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDeleteGame {
            get {
                return ResourceManager.GetString("MenuDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuJson {
            get {
                return ResourceManager.GetString("MenuJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuNewGame {
            get {
                return ResourceManager.GetString("MenuNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuRoundLog {
            get {
                return ResourceManager.GetString("MenuRoundLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSelectGame {
            get {
                return ResourceManager.GetString("MenuSelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Mail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSendMail {
            get {
                return ResourceManager.GetString("MenuSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSetting {
            get {
                return ResourceManager.GetString("MenuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettingRule {
            get {
                return ResourceManager.GetString("MenuSettingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefixGame {
            get {
                return ResourceManager.GetString("PrefixGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefixPlayer {
            get {
                return ResourceManager.GetString("PrefixPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefixRound {
            get {
                return ResourceManager.GetString("PrefixRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrefixTeam {
            get {
                return ResourceManager.GetString("PrefixTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabPlayer {
            get {
                return ResourceManager.GetString("TabPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Round に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabRound {
            get {
                return ResourceManager.GetString("TabRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1st player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text1stPlayer {
            get {
                return ResourceManager.GetString("Text1stPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2nd Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text2ndPlayer {
            get {
                return ResourceManager.GetString("Text2ndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3rd Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text3rdPlayer {
            get {
                return ResourceManager.GetString("Text3rdPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextAlert {
            get {
                return ResourceManager.GetString("TextAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BYE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBYE {
            get {
                return ResourceManager.GetString("TextBYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bye Match Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextByeMatchCount {
            get {
                return ResourceManager.GetString("TextByeMatchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Due to data corruption, Initialized settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextCorruptedData {
            get {
                return ResourceManager.GetString("TextCorruptedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dropped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextDropped {
            get {
                return ResourceManager.GetString("TextDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is only winner.　no more create matching. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextEndGame {
            get {
                return ResourceManager.GetString("TextEndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to make match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextFailToMakeMatch {
            get {
                return ResourceManager.GetString("TextFailToMakeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextGiveUp {
            get {
                return ResourceManager.GetString("TextGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to rule setting. You may modify rule setting before retry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextGoToRuleSetting {
            get {
                return ResourceManager.GetString("TextGoToRuleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version-up initialized settings.
        ///NOTE :  BSMM2 does not guarantee  persistency of your settings and logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextLegacyVersion {
            get {
                return ResourceManager.GetString("TextLegacyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Life Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextLifePoint {
            get {
                return ResourceManager.GetString("TextLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextMatchPoint {
            get {
                return ResourceManager.GetString("TextMatchPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opponent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextOpponent {
            get {
                return ResourceManager.GetString("TextOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Op-Life Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextOpponentLifePoint {
            get {
                return ResourceManager.GetString("TextOpponentLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Op-Match Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextOpponentMatchPoint {
            get {
                return ResourceManager.GetString("TextOpponentMatchPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Op-Win Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextOpponentWinPoint {
            get {
                return ResourceManager.GetString("TextOpponentWinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPlayer {
            get {
                return ResourceManager.GetString("TextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPlayerInformation {
            get {
                return ResourceManager.GetString("TextPlayerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pnayer Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPlayerName {
            get {
                return ResourceManager.GetString("TextPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPlayerParameterKey {
            get {
                return ResourceManager.GetString("TextPlayerParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextPlayerParameterValue {
            get {
                return ResourceManager.GetString("TextPlayerParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextResult {
            get {
                return ResourceManager.GetString("TextResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Timer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextStartTimer {
            get {
                return ResourceManager.GetString("TextStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextVersionCheck {
            get {
                return ResourceManager.GetString("TextVersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextWinPoint {
            get {
                return ResourceManager.GetString("TextWinPoint", resourceCulture);
            }
        }
    }
}
